config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  
  scope '/home' do
    get '/index', to: 'home#index', :as => 'home_index'
    get '/new', to: 'home#new', :as => 'new_report'
    post '/', to: 'home#create', :as => 'create_report'
  end

  devise_scope :user do
    namespace :api do
      get '/reports', to: 'report#index'
      post '/', to: 'report#create'
      post "authenticate", to: "authentication#authenticate"
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :reports
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :project
  validates :hours, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reports
  # has_secure_password
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/authentication_controller.rb
class Api::AuthenticationController < ApplicationController
	
	skip_before_action :verify_authenticity_token


	# POST authenticate
	# return user object and authentication token
	def authenticate
		user, auth_token = AuthenticateUserService.new(authentication_params[:email],
			                                          authentication_params[:password])
																								.authenticate
    
    raise StandardError, "Invalid credentials" and return if !auth_token.present?
    render json: user.as_json(only: :email).merge({ auth_token: auth_token }), status: :ok
  end 

  private

	def authentication_params
  	params.require(:credentials).permit(:email, :password)
	end
end

app/controllers/api/report_controller.rb
class Api::ReportController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authorize_user

  def index
    reports = Report.joins(:project)
                    .group("projects.name")
                    .pluck("projects.name, 
                             SUM(reports.hours),
                             MIN(reports.created_at),
                             MAX(reports.created_at)")
    result = {}
    reports.each do |report|
      result[report[0]] = {
        "TotalHoursReported" => report[1],
        "FirstReportDate" => report[2],
        "LastReportDate" => report[3]
      }
    end
    render json: result
  end

  def create
    report = Report.new(report_params.except(:email))
    report.user = @current_user
    report.save!
    head :no_content 
  end

  private

  def report_params
  	params.permit(:project_id, :email, :hours)
  end

  def authorize_user
		@current_user = AuthorizeUserService.new(request.headers).authorize
		render json: "Invalid credentials!" unless @current_user.present?
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login, :except=>[:new]

  def after_sign_in_path_for(_resource)
    home_index_path
  end

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  private

  def require_login
    redirect_to new_user_session_url unless current_user
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @time_logs = Report.where(user: current_user).includes(:user, :project)
  end

  def new
    @projects = Project.all
    @user_id = current_user.id
  end
  
  def create
    respond_to do |format|
      report = Report.new(report_params)
      if report.save
        format.html { redirect_to home_index_path, notice: "The report was created successfully" }
        format.json { render :index, status: :created }
      else
        format.html { redirect_to home_index_path, flash: { error: "Something went wrong!"  } }
        format.json { render json: report.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def report_params
    params.require(:report).permit(:project_id, :user_id, :hours)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Reported Hours</h1>
<br/>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Reporter</th>
      <th scope="col">Project</th>
      <th scope="col">Hours</th>
      <th scope="col">LogDate</th>
    </tr>
  </thead>
  <tbody>
    <% @time_logs.each_with_index do |time_log, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= time_log.user.email %></td>
        <td><%= time_log.project.name %></td>
        <td><%= time_log.hours %></td>
        <td><%= time_log.created_at %></td>
      </tr>  
    <% end %>
  </tbody>
</table>
<%= link_to "Add hours", new_report_path, class: "btn btn-info" %>
<%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-info" %> 

app/views/home/new.html.erb
<div class="col-sm-6">
  <h2>New Report</h2>
</div>

<%= form_for :report, url: create_report_path(@report), method: :post do |f| %>
  <%= f.hidden_field :user_id, { value: @user_id } %>
  <div class="form-group">
    <div class="col-sm-4">
      <%= f.text_field :hours, required: true, class: 'form-control', placeholder: "Number of hours"%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-4">
      <%= f.select :project_id, @projects.collect { |p| [ p.name, p.id ] } %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-4">
      <%= f.submit class: 'btn btn-info'  %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeLogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= (key == "error")? 'danger' : 'info' %>" role="alert">
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
  </body>

  <script type="text/javascript">
    $(".alert").delay(4000).slideUp(200, function() {
        $(this).alert('close');
    });
  </script>

</html>